@startuml
title SmartHome Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User")
System(SmartHome, "SmartHome", "Система управления и проверки температуры в доме")

System_Ext(api, "Датчики", "API датчиков")

Rel(user, SmartHome, "Использует систему")
Rel(SmartHome,api,"Вытаскивает информацию о температуре")
@enduml